import Head from 'next/head'
import Slider from 'components/slider'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Slider Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />
    </div>
  )
}

export default Home
